package projecteuler;

public class P45 {
	/**
	 * Triangle, pentagonal, and hexagonal numbers are generated by the
	 * following formulae:
	 * 
	 * Triangle Tn=n(n+1)/2 		1, 3, 6, 10, 15, ... 
	 * Pentagonal Pn=n(3*n-1)/2 	1, 5,12, 22, 35, ... 
	 * Hexagonal Hn=n(2*n-1) 		1, 6, 15, 28, 45, ... 
	 * It can be verified that T285 = P165 = H143 = 40755.
	 * 
	 * Find the next triangle number that is also pentagonal and hexagonal.
	 * 
	 */
	public static void func(){
		int p=0;
		int h=0;
		long pn = pen(p);
		long hn = hex(h);
		for (int i = 286; i<100000; i++) {
			long n=tri(i);
			//System.out.println(n);
			while(pn<n){
				p++;
				pn=pen(p);
			}
			if(pn!=n){
				continue;
			}
			while(hn<n){
				h++;
				hn=hex(h);
			}
			if(hn==n){
				System.out.println(n+" "+i);
				break;
			}
		}
	}
	public static long tri(long n){
		return n*(n+1)/2;
	}
	public static long pen(long n){
		return n*(3*n-1)/2;
	}
	public static long hex(long n){
		return n*(2*n-1);
	}
	public static boolean isTria(double num){
		float d = (float) (1+8*num);
		float n = (float)((Math.sqrt(d)+1)/2);
		if ((int) n != n)
			return false;
		return true;
	}

	public static void main(String[] args) {
		long i =System.currentTimeMillis();
		func();
		System.out.println(System.currentTimeMillis()-i);
	}

}
