package projecteuler;

public class P45 {
	/**
	 * Triangle, pentagonal, and hexagonal numbers are generated by the
	 * following formulae:
	 * 
	 * Triangle Tn=n(n+1)/2 		1, 3, 6, 10, 15, ... 
	 * Pentagonal Pn=n(3*n-1)/2 	1, 5,12, 22, 35, ... 
	 * Hexagonal Hn=n(2*n-1) 		1, 6, 15, 28, 45, ... 
	 * It can be verified that T285 = P165 = H143 = 40755.
	 * 
	 * Find the next triangle number that is also pentagonal and hexagonal.
	 * 
	 */
	public static void func(){
		for (int i = 1; i<100000; i++) {
			int n=i*(i+1)/2;
			if(isHexagonal(n) && isPenta(n)){
				System.out.println(n+" "+i);
				//break;
			}
		}
	}
	public static boolean isTria(double num){
		float d = (float) (1+8*num);
		float n = (float)((Math.sqrt(d)+1)/2);
		if ((int) n != n)
			return false;
		return true;
	}
	public static boolean isHexagonal(double num){
		float d = (float) (0.25+2*num);
		float n = (float) ((Math.sqrt(d)+0.5)/2);
		if ((int) n != n)
			return false;
		return true;
	}
	public static boolean isPenta(double num) {
		double d = 1 + 24 * num;
		double n = (float) ((Math.sqrt(d) + 1) / 6);
		if ((int) n != n){
			//System.out.println(n);
			return false;
		}
		return true;
	}

	public static void main(String[] args) {
		for (int i = 1; i < 10000; i++) {
			int n = i*(i+1)/2 ;
			if(!isTria(n)){
				System.out.println(n+" = "+i);
			}
		}
		func();
	}

}
